USE ROLE ACCOUNTADMIN

CREATE ROLE IF NOT EXISTS TRANSFORM

GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH

GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM

CREATE USER IF NOT EXISTS dbt PASSWORD='dbtPassword123' LOGIN_NAME='dbt' MUST_CHANGE_PASSWORD=FALSE DEFAULT_WAREHOUSE='COMPUTE_WH' DEFAULT_ROLE=TRANSFORM DEFAULT_NAMESPACE='AIRBNB.RAW' COMMENT='DBT user used for data transformation'

ALTER USER dbt SET TYPE = LEGACY_SERVICE

GRANT ROLE TRANSFORM to USER dbt

CREATE DATABASE IF NOT EXISTS AIRBNB

CREATE SCHEMA IF NOT EXISTS AIRBNB.RAW

GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM

GRANT ALL ON DATABASE AIRBNB to ROLE TRANSFORM

GRANT ALL ON ALL SCHEMAS IN DATABASE AIRBNB to ROLE TRANSFORM

GRANT ALL ON FUTURE SCHEMAS IN DATABASE AIRBNB to ROLE TRANSFORM

GRANT ALL ON ALL TABLES IN SCHEMA AIRBNB.RAW to ROLE TRANSFORM

GRANT ALL ON FUTURE TABLES IN SCHEMA AIRBNB.RAW to ROLE TRANSFORM